project_id = "jqyhiekqqcffiwpctzsi"

[functions.unlock-lead]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.buy-credits]
verify_jwt = false

[functions.verify-credits]
verify_jwt = false

[functions.use-credit]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false
