import { useEffect, useState } from "react";
import { Loader2, Pencil, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

const db = supabase as unknown as SupabaseClient;
interface AddOn { id:string; name:string; category:string; description:string|null; customer_price_pence:number; cleaner_payout_pence:number; duration_minutes:number; unit_label:string; max_quantity:number; is_active:boolean; display_order:number; }
const money=(pence:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100);

export function AgencyAddOnSettings(){
  const [items,setItems]=useState<AddOn[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [editing,setEditing]=useState<AddOn|null>(null);
  const load=async()=>{setLoading(true);const {data,error}=await db.from("service_addons").select("*").order("display_order");setLoading(false);if(error)return toast.error(error.message);setItems((data as AddOn[])||[]);};
  useEffect(()=>{void load();},[]);
  const toggle=async(item:AddOn,value:boolean)=>{const {error}=await db.from("service_addons").update({is_active:value,updated_at:new Date().toISOString()}).eq("id",item.id);if(error)return toast.error(error.message);setItems(current=>current.map(row=>row.id===item.id?{...row,is_active:value}:row));toast.success(value?"Add-on enabled":"Add-on hidden from quoting");};
  const save=async()=>{if(!editing)return; if(editing.customer_price_pence<editing.cleaner_payout_pence)return toast.error("Customer price must cover cleaner payout");setSaving(true);const {error}=await db.from("service_addons").update({name:editing.name,description:editing.description,customer_price_pence:editing.customer_price_pence,cleaner_payout_pence:editing.cleaner_payout_pence,duration_minutes:editing.duration_minutes,unit_label:editing.unit_label,max_quantity:editing.max_quantity,updated_at:new Date().toISOString()}).eq("id",editing.id);setSaving(false);if(error)return toast.error(error.message);toast.success("Add-on updated");setEditing(null);void load();};
  return <Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5"/>Service add-ons</CardTitle><CardDescription>Control the extras offered during customer calls. Existing quotes retain the prices originally agreed.</CardDescription></div><Button variant="outline" size="sm" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</Button></CardHeader><CardContent>{loading?<div className="flex min-h-40 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin"/></div>:<div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Add-on</TableHead><TableHead>Category</TableHead><TableHead>Customer</TableHead><TableHead>Cleaner</TableHead><TableHead>Margin</TableHead><TableHead>Time</TableHead><TableHead>Active</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{item.name}</p><p className="max-w-sm text-xs text-muted-foreground">{item.description}</p></TableCell><TableCell><Badge variant="outline">{item.category}</Badge></TableCell><TableCell>{money(item.customer_price_pence)}</TableCell><TableCell>{money(item.cleaner_payout_pence)}</TableCell><TableCell>{money(item.customer_price_pence-item.cleaner_payout_pence)}</TableCell><TableCell>{item.duration_minutes} min / {item.unit_label}</TableCell><TableCell><Switch checked={item.is_active} onCheckedChange={value=>void toggle(item,value)}/></TableCell><TableCell><Button variant="ghost" size="icon" onClick={()=>setEditing({...item})}><Pencil className="h-4 w-4"/></Button></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent>
    <Dialog open={!!editing} onOpenChange={open=>!open&&setEditing(null)}><DialogContent><DialogHeader><DialogTitle>Edit service add-on</DialogTitle><DialogDescription>Changes affect new quotes only.</DialogDescription></DialogHeader>{editing&&<div className="space-y-4"><div><Label>Name</Label><Input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></div><div><Label>Description</Label><Input value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})}/></div><div className="grid grid-cols-2 gap-4"><MoneyField label="Customer price (£)" value={editing.customer_price_pence} onChange={value=>setEditing({...editing,customer_price_pence:value})}/><MoneyField label="Cleaner payout (£)" value={editing.cleaner_payout_pence} onChange={value=>setEditing({...editing,cleaner_payout_pence:value})}/><NumberField label="Minutes per unit" value={editing.duration_minutes} onChange={value=>setEditing({...editing,duration_minutes:value})}/><NumberField label="Maximum quantity" value={editing.max_quantity} onChange={value=>setEditing({...editing,max_quantity:value})}/></div><div><Label>Unit label</Label><Input value={editing.unit_label} onChange={e=>setEditing({...editing,unit_label:e.target.value})}/></div><div className="flex justify-end"><Button onClick={()=>void save()} disabled={saving}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Save add-on</Button></div></div>}</DialogContent></Dialog>
  </Card>;
}
function MoneyField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <div><Label>{label}</Label><Input type="number" min="0" step="0.01" value={(value/100).toFixed(2)} onChange={e=>onChange(Math.round(Number(e.target.value)*100))}/></div>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <div><Label>{label}</Label><Input type="number" min="0" step="1" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>}
