import { useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { AlertTriangle, CalendarClock, Copy, ExternalLink, FileText, Loader2, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const db=supabase as unknown as SupabaseClient;
type ReviewStatus="not_submitted"|"pending_review"|"approved"|"rejected"|"replacement_required";
interface Vetting { cleaner_id:string;address_line_1:string|null;address_line_2:string|null;city:string|null;citizenship_route:string|null;date_of_birth:string|null;right_to_work_share_code:string|null;identity_status:ReviewStatus;address_status:ReviewStatus;right_to_work_status:string;right_to_work_basis:string|null;right_to_work_expires_on:string|null;right_to_work_checked_at:string|null;right_to_work_restrictions:string|null;dbs_status:string;admin_notes:string|null;submitted_at:string|null; }
interface Doc { id:string;document_type:string;file_path:string;status:string;uploaded_at:string;admin_notes:string|null;signed_url?:string; }
interface Reminder { id:string;reminder_type:string;scheduled_for:string;status:string; }
const statuses:ReviewStatus[]=["pending_review","approved","replacement_required","rejected"];
const pretty=(value:string)=>value.replace(/_/g," ").replace(/\b\w/g,(l)=>l.toUpperCase());

export function CleanerVettingPanel({cleanerId,applicationStatus,onChanged}:{cleanerId:string;applicationStatus:string;onChanged:()=>void}) {
  const [record,setRecord]=useState<Vetting|null>(null);const [docs,setDocs]=useState<Doc[]>([]);const [reminders,setReminders]=useState<Reminder[]>([]);const [busy,setBusy]=useState(false);const [revealed,setRevealed]=useState(false);const [expanded,setExpanded]=useState(false);
  const load=async()=>{const [vr,dr,rr]=await Promise.all([db.from("cleaner_vetting_records").select("*").eq("cleaner_id",cleanerId).maybeSingle(),db.from("cleaner_vetting_documents").select("id,document_type,file_path,status,uploaded_at,admin_notes").eq("cleaner_id",cleanerId).eq("is_current",true).order("uploaded_at",{ascending:false}),db.from("cleaner_compliance_reminders").select("id,reminder_type,scheduled_for,status").eq("cleaner_id",cleanerId).eq("status","scheduled").order("scheduled_for")]);const raw=(dr.data as Doc[]|null)||[];const signed=await Promise.all(raw.map(async doc=>{const {data}=await supabase.storage.from("verification-documents").createSignedUrl(doc.file_path,900);return{...doc,signed_url:data?.signedUrl};}));setRecord((vr.data as Vetting|null)||null);setDocs(signed);setReminders((rr.data as Reminder[]|null)||[]);};
  useEffect(()=>{load();},[cleanerId]);
  const days=record?.right_to_work_expires_on?Math.ceil((new Date(record.right_to_work_expires_on).getTime()-Date.now())/86400000):null;
  const alert=days!==null&&days<=92;
  const ready=record?.identity_status==="approved"&&record.address_status==="approved"&&record.right_to_work_status==="approved"&&(record.right_to_work_basis==="continuous"||!!record.right_to_work_expires_on&&new Date(record.right_to_work_expires_on)>=new Date(new Date().toDateString()));
  const docByType=useMemo(()=>Object.fromEntries(docs.map(doc=>[doc.document_type,doc])),[docs]);
  const patch=(updates:Partial<Vetting>)=>setRecord(current=>current?{...current,...updates}:current);
  const save=async()=>{if(!record)return;if(record.citizenship_route==="other"&&record.right_to_work_status==="approved"&&!record.right_to_work_expires_on)return toast.error("Set the visa/right-to-work expiry date before approval.");setBusy(true);const {error}=await db.from("cleaner_vetting_records").update({identity_status:record.identity_status,address_status:record.address_status,right_to_work_status:record.right_to_work_status,right_to_work_basis:record.citizenship_route==="other"?"time_limited":"continuous",right_to_work_expires_on:record.citizenship_route==="other"?record.right_to_work_expires_on:null,right_to_work_checked_at:record.right_to_work_status==="approved"?new Date().toISOString():null,right_to_work_restrictions:record.right_to_work_restrictions,dbs_status:record.dbs_status,admin_notes:record.admin_notes,updated_at:new Date().toISOString()}).eq("cleaner_id",cleanerId);if(!error){await Promise.all(docs.map(doc=>db.from("cleaner_vetting_documents").update({status:doc.document_type==="identity"?record.identity_status:doc.document_type==="proof_of_address"?record.address_status:doc.status,reviewed_at:new Date().toISOString()}).eq("id",doc.id)));}setBusy(false);if(error)return toast.error(error.message);toast.success("Cleaner checks saved and reminder dates refreshed");await load();onChanged();};
  const activate=async()=>{if(!record||!ready)return toast.error("Approve identity, address and applicable right-to-work checks first.");setBusy(true);try{const {error:vettingError}=await db.from("cleaner_vetting_records").update({identity_status:record.identity_status,address_status:record.address_status,right_to_work_status:record.right_to_work_status,right_to_work_basis:record.citizenship_route==="other"?"time_limited":"continuous",right_to_work_expires_on:record.citizenship_route==="other"?record.right_to_work_expires_on:null,right_to_work_checked_at:new Date().toISOString(),right_to_work_restrictions:record.right_to_work_restrictions,dbs_status:record.dbs_status,admin_notes:record.admin_notes,updated_at:new Date().toISOString()}).eq("cleaner_id",cleanerId);if(vettingError)throw vettingError;const documentUpdates=await Promise.all(docs.map(doc=>db.from("cleaner_vetting_documents").update({status:doc.document_type==="identity"?"approved":doc.document_type==="proof_of_address"?"approved":doc.status,reviewed_at:new Date().toISOString()}).eq("id",doc.id)));const documentError=documentUpdates.find(result=>result.error)?.error;if(documentError)throw documentError;const {error:profileError}=await db.from("cleaner_profiles").update({verification_status:"approved",operational_status:"active",approved_at:new Date().toISOString()}).eq("id",cleanerId);if(profileError)throw profileError;setExpanded(false);toast.success("Checks approved and cleaner activated");await load();onChanged();}catch(error){toast.error((error as Error).message||"We could not approve the checks and activate this cleaner.");}finally{setBusy(false);}};
  if(!record)return <div className="mt-4 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No structured onboarding submission yet. Existing cleaner data is preserved, but the cleaner must complete the new required checks.</div>;
  return <details open={expanded} onToggle={(event)=>setExpanded((event.currentTarget as HTMLDetailsElement).open)} className="mt-4 rounded-xl border bg-muted/20"><summary className="cursor-pointer list-none p-4 font-semibold"><span className="flex flex-wrap items-center justify-between gap-2"><span className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/>Open onboarding checks</span><span className="flex gap-2"><Badge variant="outline">{ready?"Ready to activate":"Checks incomplete"}</Badge>{alert&&<Badge className={days!==null&&days<=31?"bg-red-600":"bg-amber-500"}><AlertTriangle className="mr-1 h-3 w-3"/>{days !== null && days <= 0?"Expired":`${days} days left`}</Badge>}</span></span></summary><div className="space-y-5 border-t p-4">
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border bg-card p-4"><p className="text-xs font-semibold uppercase text-muted-foreground">Submitted address</p><p className="mt-2 text-sm">{[record.address_line_1,record.address_line_2,record.city].filter(Boolean).join(", ")||"Not supplied"}</p></div><div className="rounded-lg border bg-card p-4"><p className="text-xs font-semibold uppercase text-muted-foreground">Right-to-work route</p><p className="mt-2 text-sm font-medium">{record.citizenship_route?pretty(record.citizenship_route):"Not supplied"}</p>{record.citizenship_route==="other"&&<><p className="mt-2 text-xs text-muted-foreground">Date of birth: {record.date_of_birth?new Date(record.date_of_birth).toLocaleDateString("en-GB"):"Missing"}</p><div className="mt-2 flex items-center gap-2"><code className="rounded bg-muted px-2 py-1 text-xs">{revealed?record.right_to_work_share_code:"•••••••••"}</code><Button type="button" size="sm" variant="outline" onClick={()=>setRevealed(v=>!v)}>{revealed?"Hide":"Reveal"}</Button>{record.right_to_work_share_code&&<Button type="button" size="icon" variant="ghost" onClick={()=>navigator.clipboard.writeText(record.right_to_work_share_code||"")}><Copy className="h-4 w-4"/></Button>}</div><Button asChild size="sm" variant="link" className="mt-2 h-auto p-0"><a href="https://www.gov.uk/view-right-to-work" target="_blank" rel="noreferrer">Open Home Office checker<ExternalLink className="ml-1 h-3 w-3"/></a></Button></>}</div></div>
    <div className="grid gap-4 md:grid-cols-2">{([['identity','Identity document','identity_status'],['proof_of_address','Proof of address','address_status']] as const).map(([type,label,statusKey])=>{const doc=docByType[type];return <div key={type} className="rounded-lg border bg-card p-4"><div className="flex items-center justify-between gap-2"><div><p className="font-medium">{label}</p><p className="text-xs text-muted-foreground">{doc?`Uploaded ${new Date(doc.uploaded_at).toLocaleDateString("en-GB")}`:"Missing"}</p></div>{doc?.signed_url&&<Button asChild size="sm" variant="outline"><a href={doc.signed_url} target="_blank" rel="noreferrer"><FileText className="mr-1 h-4 w-4"/>View</a></Button>}</div><Select value={record[statusKey]} onValueChange={(value)=>patch({[statusKey]:value} as Partial<Vetting>)}><SelectTrigger className="mt-3"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(value=><SelectItem key={value} value={value}>{pretty(value)}</SelectItem>)}</SelectContent></Select></div>;})}</div>
    <div className="rounded-lg border bg-card p-4"><h4 className="font-medium">Right-to-work review</h4><div className="mt-3 grid gap-4 md:grid-cols-3"><div><Label>Status</Label><Select value={record.right_to_work_status} onValueChange={(value)=>patch({right_to_work_status:value})}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(value=><SelectItem key={value} value={value}>{pretty(value)}</SelectItem>)}</SelectContent></Select></div><div><Label>Basis</Label><Input className="mt-2" value={record.citizenship_route==="other"?"Time limited":"Continuous"} disabled/></div>{record.citizenship_route==="other"&&<div><Label htmlFor={`expiry-${cleanerId}`}>Visa/right-to-work expiry</Label><Input id={`expiry-${cleanerId}`} className="mt-2" type="date" value={record.right_to_work_expires_on||""} onChange={event=>patch({right_to_work_expires_on:event.target.value})}/></div>}</div><div className="mt-4"><Label htmlFor={`restrictions-${cleanerId}`}>Restrictions or conditions</Label><Textarea id={`restrictions-${cleanerId}`} className="mt-2" value={record.right_to_work_restrictions||""} onChange={event=>patch({right_to_work_restrictions:event.target.value})}/></div></div>
    <div className="rounded-lg border bg-card p-4"><div className="flex items-center justify-between"><div><h4 className="font-medium">DBS check</h4><p className="text-xs text-muted-foreground">Optional — this never blocks activation.</p></div><Select value={record.dbs_status} onValueChange={value=>patch({dbs_status:value})}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent>{["not_provided","pending_review","verified","rejected"].map(value=><SelectItem key={value} value={value}>{pretty(value)}</SelectItem>)}</SelectContent></Select></div></div>
    {reminders.length>0&&<div className="rounded-lg border bg-amber-50 p-4"><h4 className="flex items-center gap-2 font-medium"><CalendarClock className="h-4 w-4"/>Scheduled expiry reminders</h4><div className="mt-2 flex flex-wrap gap-2">{reminders.map(reminder=><Badge key={reminder.id} variant="outline">{pretty(reminder.reminder_type)} · {new Date(reminder.scheduled_for).toLocaleDateString("en-GB")}</Badge>)}</div></div>}
    <div><Label htmlFor={`vetting-notes-${cleanerId}`}>Admin notes</Label><Textarea id={`vetting-notes-${cleanerId}`} className="mt-2" value={record.admin_notes||""} onChange={event=>patch({admin_notes:event.target.value})}/></div><div className="flex flex-wrap gap-2"><Button onClick={save} disabled={busy}>{busy&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Save checks</Button>{applicationStatus==="approved"&&<Button onClick={activate} disabled={busy||!ready}>{busy&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Approve checks & activate</Button>}</div>
  </div></details>;
}
