UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:34px;line-height:1.2;margin:0 0 24px">Request received</h1><p style="font-size:18px;line-height:1.6">Hello {{customer_name}},</p><p style="font-size:18px;line-height:1.6">We have received your request for <strong>{{job_type}}</strong>. Our Greater Manchester team will review the details and contact you to confirm the price and booking.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p style="font-size:17px;line-height:1.6"><strong>Preferred date:</strong> {{preferred_date}}</p><p style="font-size:17px;line-height:1.6"><strong>Postcode:</strong> {{postcode}}</p><p style="font-size:17px;line-height:1.6"><strong>Reference:</strong> {{reference_id}}</p></div><p style="font-size:15px;line-height:1.6;color:#526173">Nothing is booked or charged until Cleanda confirms the price and arrangements.</p></div>
$email$, description = 'Customer confirmation when a managed cleaning request is submitted', updated_at = now()
WHERE name = 'cleaning_request_confirmation';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:34px;line-height:1.2;margin:0 0 24px">Booking confirmed</h1><p style="font-size:18px;line-height:1.6">Hello {{customer_name}},</p><p style="font-size:18px;line-height:1.6">Your payment has been received and your cleaning is booked.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Service:</strong> {{service_name}}</p><p><strong>Amount paid:</strong> {{customer_price}}</p><p><strong>Date:</strong> {{scheduled_date}} at {{start_time}}</p><p><strong>Duration:</strong> {{duration}}</p><p><strong>Request:</strong> {{request_reference}}</p><p><strong>Job:</strong> {{job_reference}}</p></div><p style="font-size:15px;line-height:1.6;color:#526173">We will keep you updated as your cleaning date approaches.</p></div>
$email$, updated_at = now() WHERE name = 'agency_payment_confirmation';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:34px;line-height:1.2;margin:0 0 24px">New job offer</h1><p style="font-size:18px;line-height:1.6">Hi {{cleaner_name}},</p><p style="font-size:18px;line-height:1.6">A new cleaning job is available for you.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Service:</strong> {{service_name}}</p><p><strong>Date:</strong> {{scheduled_date}} at {{start_time}}</p><p><strong>Duration:</strong> {{duration}}</p><p><strong>Area:</strong> {{postcode}}</p><p><strong>Your payout:</strong> {{cleaner_payout}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div><p style="font-size:17px;line-height:1.6">Open your Cleanda dashboard to accept or decline. The full address is released only after acceptance.</p><p><a href="{{dashboard_url}}" style="display:inline-block;background:#16a765;color:white;padding:14px 24px;border-radius:8px;text-decoration:none;font-weight:bold">View job offer</a></p></div>
$email$, variables = ARRAY['cleaner_name','service_name','scheduled_date','start_time','duration','postcode','cleaner_payout','job_reference','dashboard_url'], updated_at = now() WHERE name = 'cleaner_job_offer';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:34px;line-height:1.2;margin:0 0 24px">Job confirmed</h1><p style="font-size:18px;line-height:1.6">Hi {{cleaner_name}},</p><p style="font-size:18px;line-height:1.6">You have accepted this job. The complete details are below.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Service:</strong> {{service_name}}</p><p><strong>Date:</strong> {{scheduled_date}} at {{start_time}}</p><p><strong>Duration:</strong> {{duration}}</p><p><strong>Address:</strong> {{full_address}}</p><p><strong>Access:</strong> {{access_notes}}</p><p><strong>Instructions:</strong> {{instructions}}</p><p><strong>Your payout:</strong> {{cleaner_payout}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div><p><a href="{{dashboard_url}}" style="display:inline-block;background:#16a765;color:white;padding:14px 24px;border-radius:8px;text-decoration:none;font-weight:bold">Open cleaner dashboard</a></p></div>
$email$, variables = ARRAY['cleaner_name','customer_name','service_name','scheduled_date','start_time','duration','full_address','access_notes','instructions','cleaner_payout','job_reference','dashboard_url'], updated_at = now() WHERE name = 'cleaner_assignment_confirmed';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:32px;margin:0 0 24px">Job in 3 days</h1><p style="font-size:18px;line-height:1.6">Hi {{cleaner_name}}, your {{service_name}} job for {{customer_name}} is coming up.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Date:</strong> {{scheduled_date}} at {{start_time}}</p><p><strong>Address:</strong> {{full_address}}</p><p><strong>Duration:</strong> {{duration}}</p><p><strong>Payout:</strong> {{cleaner_payout}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div></div>
$email$, updated_at = now() WHERE name = 'cleaner_reminder_3_day';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:32px;margin:0 0 24px">Job tomorrow</h1><p style="font-size:18px;line-height:1.6">Hi {{cleaner_name}}, your {{service_name}} job for {{customer_name}} is tomorrow.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Start time:</strong> {{start_time}}</p><p><strong>Address:</strong> {{full_address}}</p><p><strong>Duration:</strong> {{duration}}</p><p><strong>Payout:</strong> {{cleaner_payout}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div></div>
$email$, updated_at = now() WHERE name = 'cleaner_reminder_1_day';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:32px;margin:0 0 24px">Your job is today</h1><p style="font-size:18px;line-height:1.6">Hi {{cleaner_name}}, your {{service_name}} job for {{customer_name}} starts at {{start_time}}.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Address:</strong> {{full_address}}</p><p><strong>Access:</strong> {{access_notes}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div><p style="font-size:15px;color:#526173">Remember to check in and upload the required before-and-after evidence.</p></div>
$email$, updated_at = now() WHERE name = 'cleaner_reminder_day';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:32px;margin:0 0 24px">Your cleaning is in 3 days</h1><p style="font-size:18px;line-height:1.6">Hi {{customer_name}}, this is a reminder that your {{service_name}} is coming up.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Date:</strong> {{scheduled_date}} at {{start_time}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div><p style="font-size:15px;color:#526173">Please ensure the cleaner can access the property at the confirmed time.</p></div>
$email$, updated_at = now() WHERE name = 'customer_reminder_3_day';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:32px;margin:0 0 24px">Your cleaning is tomorrow</h1><p style="font-size:18px;line-height:1.6">Hi {{customer_name}}, your {{service_name}} is scheduled for tomorrow.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Start time:</strong> {{start_time}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div><p style="font-size:15px;color:#526173">Please ensure the cleaner can access the property at the confirmed time.</p></div>
$email$, updated_at = now() WHERE name = 'customer_reminder_1_day';

UPDATE public.email_templates SET body = $email$
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#102235"><div style="border-bottom:4px solid #16a765;padding:0 0 18px;margin-bottom:28px"><strong style="font-size:24px">Cleanda</strong></div><h1 style="font-size:32px;margin:0 0 24px">Your cleaning is today</h1><p style="font-size:18px;line-height:1.6">Hi {{customer_name}}, your {{service_name}} is scheduled today.</p><div style="padding:20px;background:#f4faf7;border-radius:12px;margin:24px 0"><p><strong>Start time:</strong> {{start_time}}</p><p><strong>Reference:</strong> {{job_reference}}</p></div><p style="font-size:15px;color:#526173">Our team is here if you need any help with today’s booking.</p></div>
$email$, updated_at = now() WHERE name = 'customer_reminder_day';

UPDATE public.email_templates SET
  subject = 'Cleanda job today — {{job_reference}}',
  body = 'Cleanda: {{service_name}} for {{customer_name}} is today at {{start_time}}. Address: {{full_address}}. Ref: {{job_reference}}.',
  updated_at = now()
WHERE name = 'cleaner_reminder_day_sms';

INSERT INTO public.platform_schema_versions(version, description)
VALUES ('20260816313000', 'Polished Cleanda visual system for all managed-agency communications')
ON CONFLICT (version) DO UPDATE SET description = excluded.description;

NOTIFY pgrst, 'reload schema';