import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Camera, CheckCircle2, ClipboardCheck, Loader2, Plus, RefreshCw, ShieldAlert } from "lucide-react";
import type { SupabaseClient } from "@supabase/supabase-js";
import AdminLayout from "@/components/admin/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const db = supabase as unknown as SupabaseClient;
type Job = { id:string; reference:string; status:string; quality_review_status:string; quality_review_notes:string|null; cleaner_completion_notes:string|null; scheduled_date:string; customer_amount_pence:number; cleaner_payout_pence:number; customer:{name:string;phone:string}|null; address:{address_line_1:string|null;address_line_2:string|null;city:string|null;postcode:string;access_notes:string|null}|null; service_type:{name:string}|null; assignments:{status:string;cleaner:{full_name:string|null;phone:string|null}|null}[]; payouts:{status:string;held_reason:string|null}[] };
type Issue = { id:string;job_id:string;source:string;category:string;severity:string;status:string;summary:string;description:string|null;resolution_notes:string|null;due_at:string|null;created_at:string;job:Job };
type Evidence = { id:string;job_id:string;evidence_type:string;storage_path:string;signedUrl?:string };
const money=(v:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(v/100);
const openStatuses=["open","investigating","awaiting_customer","awaiting_cleaner","rework_required"];

export default function AdminQualityIssues(){
  const [jobs,setJobs]=useState<Job[]>([]),[issues,setIssues]=useState<Issue[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[tab,setTab]=useState("review");
  const [reviewJob,setReviewJob]=useState<Job|null>(null),[reviewNotes,setReviewNotes]=useState("");
  const [newIssueJob,setNewIssueJob]=useState<Job|null>(null),[selectedIssue,setSelectedIssue]=useState<Issue|null>(null);
  const [issueForm,setIssueForm]=useState({source:"customer_complaint",category:"cleaning_quality",severity:"medium",summary:"",description:"",due_at:""});
  const [issueStatus,setIssueStatus]=useState("investigating"),[resolution,setResolution]=useState("");
  const loadedOnce=useRef(false);
  const fetchData=async()=>{
    if(!loadedOnce.current)setLoading(true);
    const jobSelect="id,reference,status,quality_review_status,quality_review_notes,cleaner_completion_notes,scheduled_date,customer_amount_pence,cleaner_payout_pence,customer:customers(name,phone),address:customer_addresses(address_line_1,address_line_2,city,postcode,access_notes),service_type:service_types(name),assignments:job_assignments(status,cleaner:cleaner_profiles(full_name,phone)),payouts:cleaner_payouts(status,held_reason)";
    const [jr,ir,er]=await Promise.all([
      db.from("jobs").select(jobSelect).in("status",["quality_check","issue","completed"]).order("scheduled_date",{ascending:false}),
      db.from("job_issues").select(`id,job_id,source,category,severity,status,summary,description,resolution_notes,due_at,created_at,job:jobs(${jobSelect.replace(/^id,/,"")})`).order("created_at",{ascending:false}),
      db.from("job_evidence").select("id,job_id,evidence_type,storage_path").order("created_at",{ascending:true})
    ]);
    loadedOnce.current=true;setLoading(false);
    if(jr.error||ir.error||er.error)return toast.error(jr.error?.message||ir.error?.message||er.error?.message||"Could not load quality workspace");
    setJobs((jr.data as unknown as Job[])||[]);setIssues((ir.data as unknown as Issue[])||[]);
    const signed=await Promise.all(((er.data as Evidence[])||[]).map(async item=>{const {data}=await supabase.storage.from("job-evidence").createSignedUrl(item.storage_path,3600);return {...item,signedUrl:data?.signedUrl};}));setEvidence(signed);
  };
  useEffect(()=>{fetchData();},[]);
  const reviewQueue=jobs.filter(j=>j.status==="quality_check"),activeIssues=issues.filter(i=>openStatuses.includes(i.status));
  const held=jobs.filter(j=>j.payouts?.some(p=>p.status==="held")).length;
  const photos=(jobId:string)=>evidence.filter(e=>e.job_id===jobId);
  const activeCleaner=(job:Job)=>job.assignments?.find(a=>["accepted","completed"].includes(a.status))?.cleaner;
  const runReview=async(decision:"approved"|"rework_required"|"issue")=>{if(!reviewJob)return;if(decision!=="approved"&&reviewNotes.trim().length<5)return toast.error("Add clear notes for the cleaner and audit record.");setSaving(true);const {error}=await db.rpc("admin_review_job_completion",{p_job_id:reviewJob.id,p_decision:decision,p_notes:reviewNotes||null});setSaving(false);if(error)return toast.error(error.message);toast.success(decision==="approved"?"Job approved and payout updated":decision==="rework_required"?"Rework requested and payout held":"Job moved to issue investigation");setReviewJob(null);setReviewNotes("");fetchData();};
  const createIssue=async()=>{if(!newIssueJob||issueForm.summary.trim().length<3)return toast.error("Add an issue summary.");setSaving(true);const {error}=await db.rpc("create_job_issue",{p_job_id:newIssueJob.id,p_source:issueForm.source,p_category:issueForm.category,p_severity:issueForm.severity,p_summary:issueForm.summary,p_description:issueForm.description||null,p_due_at:issueForm.due_at?new Date(issueForm.due_at).toISOString():null});setSaving(false);if(error)return toast.error(error.message);toast.success("Issue opened and payout held");setNewIssueJob(null);setIssueForm({source:"customer_complaint",category:"cleaning_quality",severity:"medium",summary:"",description:"",due_at:""});setTab("issues");fetchData();};
  const updateIssue=async()=>{if(!selectedIssue)return;setSaving(true);const {error}=await db.rpc("update_job_issue",{p_issue_id:selectedIssue.id,p_status:issueStatus,p_resolution_notes:resolution||null});setSaving(false);if(error)return toast.error(error.message);toast.success("Issue and job pipeline updated");setSelectedIssue(null);setResolution("");fetchData();};
  const summary=[["Awaiting review",reviewQueue.length,ClipboardCheck],["Open issues",activeIssues.length,ShieldAlert],["High priority",activeIssues.filter(i=>["high","critical"].includes(i.severity)).length,AlertTriangle],["Payouts held",held,CheckCircle2]] as const;
  const issueCards=(items:Issue[])=>items.length?<div className="grid gap-4 xl:grid-cols-2">{items.map(i=><button key={i.id} onClick={()=>{setSelectedIssue(i);setIssueStatus(i.status);setResolution(i.resolution_notes||"");}} className="rounded-xl border bg-card p-5 text-left shadow-sm transition hover:border-primary/50"><div className="flex flex-wrap items-center gap-2"><strong>{i.job?.reference}</strong><Badge variant={i.severity==="critical"?"destructive":"outline"}>{i.severity}</Badge><Badge variant="secondary">{i.status.replace(/_/g," ")}</Badge></div><h3 className="mt-3 font-semibold">{i.summary}</h3><p className="mt-1 text-sm text-muted-foreground">{i.job?.customer?.name} · {i.job?.service_type?.name} · {i.category.replace(/_/g," ")}</p>{i.description&&<p className="mt-3 line-clamp-2 text-sm">{i.description}</p>}</button>)}</div>:<div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">Nothing in this queue.</div>;
  return <AdminLayout title="Quality & Issues"><div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Quality & Issues</h1><p className="text-muted-foreground">Approve evidence, manage complaints, control rework and protect payouts.</p></div><Button variant="outline" onClick={fetchData}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.map(([label,value,Icon])=><div key={label} className="rounded-xl border bg-card p-4"><Icon className="h-5 w-5 text-primary"/><p className="mt-3 text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></div>)}</div>
    {loading?<Loader2 className="h-7 w-7 animate-spin"/>:<Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="review">Quality review ({reviewQueue.length})</TabsTrigger><TabsTrigger value="issues">Open issues ({activeIssues.length})</TabsTrigger><TabsTrigger value="resolved">Resolved</TabsTrigger></TabsList>
      <TabsContent value="review" className="mt-5 space-y-3">{reviewQueue.length?reviewQueue.map(job=><div key={job.id} className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><strong>{job.reference}</strong><Badge>{job.quality_review_status.replace(/_/g," ")}</Badge></div><p className="mt-2">{job.customer?.name} · {job.service_type?.name}</p><p className="text-sm text-muted-foreground">{job.scheduled_date} · {job.address?.postcode} · Cleaner: {activeCleaner(job)?.full_name||"Unassigned"}</p><p className="mt-2 text-sm">{photos(job.id).length} evidence files · Payout {money(job.cleaner_payout_pence)}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setNewIssueJob(job)}><Plus className="mr-2 h-4 w-4"/>Complaint / issue</Button><Button onClick={()=>{setReviewJob(job);setReviewNotes(job.quality_review_notes||"");}}><Camera className="mr-2 h-4 w-4"/>Review evidence</Button></div></div></div>):<div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">No jobs are waiting for quality review.</div>}</TabsContent>
      <TabsContent value="issues" className="mt-5">{issueCards(activeIssues)}</TabsContent><TabsContent value="resolved" className="mt-5">{issueCards(issues.filter(i=>!openStatuses.includes(i.status)))}</TabsContent></Tabs>}
    <Dialog open={!!reviewJob} onOpenChange={v=>!v&&setReviewJob(null)}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>Quality review · {reviewJob?.reference}</DialogTitle><DialogDescription>Check before/after proof and completion notes before releasing earnings.</DialogDescription></DialogHeader>{reviewJob&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{photos(reviewJob.id).map(p=>p.signedUrl?<a key={p.id} href={p.signedUrl} target="_blank" rel="noreferrer"><img src={p.signedUrl} alt={`${p.evidence_type} evidence`} className="aspect-square w-full rounded-lg border object-cover"/><Badge className="mt-1">{p.evidence_type}</Badge></a>:null)}</div><div className="rounded-lg bg-muted p-4 text-sm"><strong>Cleaner completion notes</strong><p className="mt-1">{reviewJob.cleaner_completion_notes||"No notes supplied."}</p></div><div><Label>Review notes</Label><Textarea value={reviewNotes} onChange={e=>setReviewNotes(e.target.value)} placeholder="Required for rework or an issue"/></div><DialogFooter className="flex-wrap"><Button variant="destructive" onClick={()=>runReview("issue")} disabled={saving}>Flag issue</Button><Button variant="outline" onClick={()=>runReview("rework_required")} disabled={saving}>Request rework</Button><Button onClick={()=>runReview("approved")} disabled={saving}>Approve & release</Button></DialogFooter></>}</DialogContent></Dialog>
    <Dialog open={!!newIssueJob} onOpenChange={v=>!v&&setNewIssueJob(null)}><DialogContent><DialogHeader><DialogTitle>Open issue · {newIssueJob?.reference}</DialogTitle><DialogDescription>This immediately holds unpaid cleaner earnings and moves the job into investigation.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div><Label>Source</Label><Select value={issueForm.source} onValueChange={v=>setIssueForm(f=>({...f,source:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["customer_complaint","quality_review","cleaner_report","admin"].map(v=><SelectItem key={v} value={v}>{v.replace(/_/g," ")}</SelectItem>)}</SelectContent></Select></div><div><Label>Severity</Label><Select value={issueForm.severity} onValueChange={v=>setIssueForm(f=>({...f,severity:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["low","medium","high","critical"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><div><Label>Category</Label><Select value={issueForm.category} onValueChange={v=>setIssueForm(f=>({...f,category:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["cleaning_quality","damage","access","lateness","conduct","missing_item","other"].map(v=><SelectItem key={v} value={v}>{v.replace(/_/g," ")}</SelectItem>)}</SelectContent></Select></div><div><Label>Due date</Label><Input type="datetime-local" value={issueForm.due_at} onChange={e=>setIssueForm(f=>({...f,due_at:e.target.value}))}/></div></div><div><Label>Summary</Label><Input value={issueForm.summary} onChange={e=>setIssueForm(f=>({...f,summary:e.target.value}))}/></div><div><Label>Full details</Label><Textarea value={issueForm.description} onChange={e=>setIssueForm(f=>({...f,description:e.target.value}))}/></div><DialogFooter><Button onClick={createIssue} disabled={saving}>Open issue & hold payout</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!selectedIssue} onOpenChange={v=>!v&&setSelectedIssue(null)}><DialogContent><DialogHeader><DialogTitle>{selectedIssue?.summary}</DialogTitle><DialogDescription>{selectedIssue?.job?.reference} · {selectedIssue?.job?.customer?.name} · Cleaner {selectedIssue&&activeCleaner(selectedIssue.job)?.full_name}</DialogDescription></DialogHeader><p className="text-sm">{selectedIssue?.description||"No additional description."}</p><div><Label>Workflow status</Label><Select value={issueStatus} onValueChange={setIssueStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[...openStatuses,"resolved","closed"].map(v=><SelectItem key={v} value={v}>{v.replace(/_/g," ")}</SelectItem>)}</SelectContent></Select></div><div><Label>Update / resolution notes</Label><Textarea value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Required when resolving or closing"/></div><DialogFooter><Button onClick={updateIssue} disabled={saving}>Save workflow update</Button></DialogFooter></DialogContent></Dialog>
  </div></AdminLayout>;
}
